spring.application.name=projeto-spring
spring.profiles.active=test
spring.jpa.open-in-view=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.show-actuator=true